data-platform:
  outputs:
    dev:
      account: ngb11331
      database: DWH
      authenticator: externalbrowser
      role: DATA-TEAM
      schema:  '{{ env_var(''USER_SCHEMA'') }}'
      threads: 1
      type: snowflake
      user: '{{ env_var(''SNOWFLAKE_USER'') }}'
      warehouse: PROD-US-WEST-1-INGESTION
  target: dev